export const imageData = [
    {
        id: 1,
        title: "Dancers at dawn",
        price: "$200",
        src: "DALL·E-13.03.25.png",
    },
    {
        id: 2,
        title: "Trees at rest",
        price: "$200",
        src: "DALL·E-14.02.24.png",
    },
    {
        id: 3,
        title: "The river denial",
        price: "$500",
        src: "DALL·E-14.04.06.png",
    },
    {
        id: 4,
        title: "Mallard",
        price: "$150",
        src: "DALL·E-14.04.57.png",
    },
    {
        id: 5,
        title: "Joy",
        price: "$700",
        src: "DALL·E-14.06.43.png",
    },
    {
        id: 6,
        title: "About town",
        price: "$600",
        src: "DALL·E-14.07.43.png",
    },
    {
        id: 7,
        title: "Serenity",
        price: "$300",
        src: "DALL·E-14.07.48.png",
    },
    {
        id: 8,
        title: "Hans Gruber Anderson",
        price: "$700",
        src: "DALL·E-14.08.50.png",
    },
    {
        id: 9,
        title: "Eight 'o clock",
        price: "$300",
        src: "DALL·E-14.09.00.png",
    },
    {
        id: 10,
        title: "George",
        price: "$250",
        src: "DALL·E-14.10.43.png",
    },
    {
        id: 11,
        title: "Pete the Pup",
        price: "$300",
        src: "DALL·E-14.10.46.png",
    },
    {
        id: 12,
        title: "Jack Mays",
        price: "$750",
        src: "DALL·E-14.12.37.png",
    },
    {
        id: 13,
        title: "Willmington",
        price: "$300",
        src: "DALL·E-14.12.40.png",
    },
    {
        id: 15,
        title: "Ivory and Magenta",
        price: "$750",
        src: "DALL·E-14.14.43.png",
    },
    {
        id: 16,
        title: "Watermelon wings",
        price: "$200",
        src: "DALL·E-14.16.04.png",
    },
    {
        id: 17,
        title: "Scented breeze",
        price: "$300",
        src: "DALL·E-14.17.23.png",
    },
    {
        id: 18,
        title: "Anabelle Lake",
        price: "$500",
        src: "DALL·E-14.20.29.png",
    },
]
